### ISSUE TITLE
In case of "command get_passphrase failed: Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by jjperezaguinaga** [pstadler/keybase-gpg-github#11]
For some reason I had to setup the GPG TTY variable on my bash when I tried to sign my commit (i.e. *-S* flag) because of passphrase, which is new to me since I usually have the passphrase prompt within my terminal, so who knows, might be a new GPG version.

Anyway, fixed it with:
```
GPG_TTY=$(tty)
export GPG_TTY
```

Might be worth adding it to the `README.md` under common issues and/or what not.

**Comment by benbieler** [comment]
Jup. Just had the same Problem. Fixed it as mentioned here.

**Comment by pstadler** [comment]
Care to open a pull request? 🍻

**Comment by jjperezaguinaga** [comment]
@pstadler #13

**Comment by johnmathews** [comment]
I have this problem also. Thanks for the fix.

**Comment by rayrutjes** [comment]
Still accurate ;)
Is there an easy way to remember the passphrase on OSX?

**Comment by roln** [comment]
thanks a lot ! Fixed it

**Comment by kavdev** [comment]
I ran into this when attempting to use gpg2 (with gpg-agent) when signing commits in git on WSL bash. Thanks for the solution.

Git's error output:
```
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by chenxiaojie** [comment]
thks

**Comment by zw201913** [comment]
thanks a lot ! Fixed it

**Comment by jgillich** [comment]
Also getting this in WSL after every system restart. Does anyone know what could be causing it?
