### ISSUE TITLE
Passphrase timeout

### ISSUE THREAD

**Issue by maschwenk** [pstadler/keybase-gpg-github#14]
It seems the passphrase is only kept for a few seconds. Is there a way to increase this? I've tried a bunch of stuff like `default-ttl` etc. but none of those seem to have worked for me.

**Comment by pstadler** [comment]
Sorry, I missed that one. Could you solve this problem?

**Comment by maschwenk** [comment]
Yeah I think it was just solved by restarting my computer 👍

**Comment by pstadler** [comment]
Good to know 👍
