### ISSUE TITLE
Instructions for pinentry-mac seem to be unnecessary on Sierra

### ISSUE THREAD

**Issue by RobinDaugherty** [pstadler/keybase-gpg-github#15]
I'm on Sierra and had previously installed gpg using Homebrew, but I hadn't done anything further to configure gpg-agent. My `.gnupg/gpg-agent.conf` had the following in it:

```
pinentry-program /Library/Frameworks/Libmacgpg.framework/Versions/A/Resources/pinentry-mac.app/Contents/MacOS/pinentry-mac
```

This seems to work correctly without any further steps, in other words, I'm able to use `git commit -S` without being prompted for the key password.

Can anyone confirm that Sierra makes this section unnecessary?

**Comment by pstadler** [comment]
Thanks Robin, I thought it was just my local setup that never asked for password...

Sorry for the late answer, sometimes my emails seem to get sucked into `/dev/null`
