### ISSUE TITLE
Doesn't seem to play ball with GitHub Desktop & PyCharm

### ISSUE THREAD

**Issue by jamesstidard** [pstadler/keybase-gpg-github#18]
I followed the steps and seemed to get everything to work apart from GitHub Desktop client and PyCharm (I assume fixing GitHub Desktop will fix PyCharm as they both show the same error: "gpg failed to sign the data fatal: failed to write commit object".

Committing using the CLI doesn't prompt me for a password each time either.

Anyone have any ideas on fixing/debugging this?

**Comment by jamesstidard** [comment]
So, it looks as though I also had to [disable no-tty](https://github.com/pstadler/keybase-gpg-github#optional-disable-tty) even though I had originally successfully [setup tty](https://github.com/pstadler/keybase-gpg-github#optional-setting-up-tty).

**Comment by pstadler** [comment]
Glad you managed to solve this.

Related:
- http://stackoverflow.com/questions/36557222/intellij-fails-to-commit-changes-when-attempting-to-sign-commit-gpg
- http://stackoverflow.com/questions/37760987/android-studio-and-git-how-do-i-gpg-sign-my-commits
