### ISSUE TITLE
Is there an extra step to get pinentry-mac to save to Keychain?

### ISSUE THREAD

**Issue by lucymhdavies** [pstadler/keybase-gpg-github#19]
> Now git commit -S, it will ask your password and you can save it to macOS keychain.

Implies that I should get a "Save in Keychain" option, similar to what I see on here
https://gpgtools.tenderapp.com/kb/faq/password-management

![pinentry_save_in_keychain](https://cloud.githubusercontent.com/assets/1116529/25059366/9152a648-217d-11e7-930a-3a82c3834466.jpg)

However, I see only the following:

<img width="549" alt="screen shot 2017-04-15 at 01 49 01" src="https://cloud.githubusercontent.com/assets/1116529/25059379/bc8b7d30-217d-11e7-920c-802b2f09d9b1.png">

**Comment by lucymhdavies** [comment]
I've just tried installing from https://gpgtools.org/#gpgsuite , as opposed to with homebrew, and I am now given the option to save to keychain.

I'll see if this works. It's working well so far at least.

**Comment by pstadler** [comment]
Please reopen if this is still an issue.

**Comment by lucymhdavies** [comment]
I've had no issues since installing gpgtools. :)

However, the instructions suggest installing just gpg-agent and pinentry-mac with homebrew, which did not work in my case.

So I'll add an extra section at the bottom with instructions for using that.

**Comment by 0x3333** [comment]
Hi! I'd like to share my experience here for someone in the future.

I'm using `GnuPG` from `brew`, and my `pinentry-mac` did not show the "Save in Keychain" option. The problem is with a missing preference:

```
defaults write org.gpgtools.pinentry-mac DisableKeychain -bool no
```

Without this option set to `no`/`false`, it will not show the option to save to KeyChain.

Hope it helps.

**Comment by benthamite** [comment]
The above steps didn't work for me. What did work was installing an earlier version of `pinentry-mac`.

- `$ brew uninstall pinentry-mac`
  - you may have to run `$ brew uninstall --ignore-dependencies pinentry-mac` if you have other apps that depend on `pinentry-mac`
- go [here](https://raw.githubusercontent.com/Homebrew/homebrew-core/8af815f97f54750fbe396ae4e8d86adfa12559a3/Formula/pinentry-mac.rb), download the file, then `$ brew install /path/to/file/pinentry-mac.rb`
- `$ brew pin pinentry-mac`, to prevent `brew` from downloading the most recent version when upgrading.

**Comment by inakiabt** [comment]
FYI, in my case it worked only after running:
```
killall gpg-agent
killall gpg2
killall gpg
killall dirmngr
```

**Comment by Dreistein75** [comment]
> Hi! I'd like to share my experience here for someone in the future.
> 
> I'm using `GnuPG` from `brew`, and my `pinentry-mac` did not show the "Save in Keychain" option. The problem is with a missing preference:
> 
> ```
> defaults write org.gpgtools.pinentry-mac DisableKeychain -bool no
> ```
> 
> Without this option set to `no`/`false`, it will not show the option to save to KeyChain.
> 
> Hope it helps.

where do you have to put this command? Simply run it in the terminal has no effect.

**Comment by 0x3333** [comment]
> > Hi! I'd like to share my experience here for someone in the future.
> > I'm using `GnuPG` from `brew`, and my `pinentry-mac` did not show the "Save in Keychain" option. The problem is with a missing preference:
> > ```
> > defaults write org.gpgtools.pinentry-mac DisableKeychain -bool no
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Without this option set to `no`/`false`, it will not show the option to save to KeyChain.
> > Hope it helps.
> 
> where do you have to put this command? Simply run it in the terminal has no effect.

See @inakiabt  comment... 

https://github.com/pstadler/keybase-gpg-github/issues/19#issuecomment-1205583356

**Comment by svenjacobs** [comment]
I don't know when this started but the password dialog regularly pops up even though the checkbox "Save in keychain" is always selected. This stops only after running `killall gpg-agent` until I restart the MacBook. Then the dialog reappears.

```
❯ gpg-agent --version
gpg-agent (GnuPG) 2.4.3
libgcrypt 1.10.3

❯ pinentry-mac --version
pinentry-mac (pinentry) 1.1.1
```

Has anyone an idea what's going on and knows a permanent solution to this problem?

macOS Sonoma 14.2.1 (23C71)

**Comment by bericp1** [comment]
> I don't know when this started but the password dialog regularly pops up even though the checkbox "Save in keychain" is always selected. This stops only after running `killall gpg-agent` until I restart the MacBook. Then the dialog reappears.
> 
> ```
> ❯ gpg-agent --version
> gpg-agent (GnuPG) 2.4.3
> libgcrypt 1.10.3
> 
> ❯ pinentry-mac --version
> pinentry-mac (pinentry) 1.1.1
> ```
> 
> Has anyone an idea what's going on and knows a permanent solution to this problem?
> 
> macOS Sonoma 14.2.1 (23C71)

I'm also having this issue. Feels like some kind of race condition. I noticed that `ps aux | grep gpg` shows a hanging `/usr/local/MacGPG2/libexec/shutdown-gpg-agent` (??) that started at last reboot:

```
ps aux | grep gpg
brandon           2717   0.0  0.0 435299840    480   ??  S    Mon05PM   0:00.01 /bin/bash /usr/local/MacGPG2/libexec/shutdown-gpg-agent
brandon          37126   0.0  0.0 410059408    112 s003  R+    1:41PM   0:00.00 grep gpg
```

And if I kill that process explicitly, it doesn't come back and pinentry doesn't prompt at all on the next use (a git commit). Feels like maybe a race condition of some sort.

I'm on Tahoe `26.5.1 (25F80)`
