### ISSUE TITLE
Brew cask install gpg-suite 

### ISSUE THREAD

**Issue by philfreo** [pstadler/keybase-gpg-github#25]
To have your key passphrase stored in the macOS Keychain, GitHub recommends using GPG Suite according to https://help.github.com/articles/signing-commits-using-gpg/

Like the rest of your instructions, this can be installed via brew with:
`brew cask install gpg-suite`

This may be a better first option/default than your existing Method 1 listed in https://github.com/pstadler/keybase-gpg-github#optional-in-case-youre-prompted-to-enter-the-password-every-time, and I don't think the subsequent steps (open Preferences, change config file) that you have for your existing Method 2 are necessary

**Comment by lucymhdavies** [comment]
Awesome. I'll have to give that a try.

**Comment by philfreo** [comment]
After posting this, I did have some trouble with my setup later and I don't remember exactly what I did to fix it. So not sure about the last paragraph of my Issue above, however I would still recommend installing via `brew cask install gpg-suite`

**Comment by pstadler** [comment]
Would you mind opening a PR for that?
